### ISSUE TITLE
Стрим из эвентов

### ISSUE THREAD

**Issue by NikitaRzm** [Burize/RxjsTodoList#1]
https://github.com/Burize/RxjsTodoList/blob/master/src/components/Todos/Todos.tsx#L53

Можем ли вот тут замутить не императивную обработку, а получать с каждого пропса по сути стрим эвента и применять к ним операции?)
Что-то типа:
```react
onClick={asStream(this.addingTodo)}
// 
addingTodo(source) {
    return source.map(evt => this.props.addTodo(evt.target.value));
}
```

**Comment by Burize** [comment]
Если правильно понял, что имелось ввиду, то это реализовано в другой репе https://github.com/Burize/reactive-todo-list .
